version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:11.7.0
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "88:67:80:fc:5c:92:95:0a:f0:a3:36:24:7f:03:34:33"
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      # run deploy!
      - deploy:
          name: Deploy
          command: yarn deploy
